### ISSUE TITLE
workbox wizard --injectManifest does not create the "swSrc" in workbox.config

### ISSUE THREAD

**Issue by didierjeanson** [googlecodelabs/workbox-lab#35] opened 2020-07-22 19:44 UTC
Here is the content of workbox-config.js at step 5
module.exports = {
  "globDirectory": "build/",
  "globPatterns": [
    "**/*.css"
  ],
  "swDest": "build/sw.js"
};

so the build fail with 
```
Your configuration is invalid:
{
  "globDirectory": "build/",
  "globPatterns": [
    "**/*.css"
  ],
  "swDest": "build/sw.js",
  "swSrc" [1]: -- missing --
}

[1] "swSrc" is required
```
I had to copy the workbox-config.js content at step 7 and it is working fine.

**Comment by DavidScales** [comment] 2020-07-23 19:01
Hi didierjeanson, 

Thanks for filing this feedback. 

My output for the [5th step](https://codelabs.developers.google.com/codelabs/workbox-lab/#4) looks like:

```
module.exports = {
  "globDirectory": "build/",
  "globPatterns": [
    "**/*.{jpg,svg,html,js,css}"
  ],
  "swDest": "build/sw.js",
  "swSrc": "src/sw.js"
};
```

Did you enter **src/sw.js** as described in the prompt?

> The third prompt asks for the path to your source service worker. This is the service worker file, src/sw.js, to which we added code in the previous step. Type "src/sw.js" and press return.

I don't believe **workbox-config.js** will even generate without a source specified (at least I can't reproduce that). Is it possible you are using a different version than workbox-cli@3.0.0?

**Comment by didierjeanson** [comment] 2020-07-23 19:11
Hi DavidScales, 
I am not asked for the third prompt !!! that's why the value is not present.

here is the output of my prompts/selection.
? What is the root of your web app (i.e. which directory do you deploy)? build/
? Which file types would you like to precache? css
? Where would you like your service worker file to be saved? build/sw.js
? Where would you like to save these configuration options? workbox-config.js

I am using workbox-cli@3.6.3.

**Comment by DavidScales** [comment] 2020-07-23 19:29
Ah I see. That is frustrating. In that case I would try v3.0.0, and see if the prompt is there. Otherwise it seems to be more of a bug in the workbox library. 

I think since 3.0.0 works and is the version used in this lab, I'll close the issue. But if you don't have success with that version let me know. 

That said, Workbox in production is on version 5 by now (the lab is a little old) so I would not stress too much about the specific API. I would recommend using the lab just to master the concept of using workbox in your site, and then when you want to get into the details or use it in a production site I would recommend switching to the updated v5. 

Hope that helps!

**Closed by DavidScales** 2020-07-23 19:29 UTC
